version: "3.9"

services:
  web:
    image: ghcr.io/${GITHUB_REPOSITORY}/web:production
    container_name: mulai-plus-web-production
    ports:
      - "${PORT_WEB:-3002}:3000"
    expose:
      - "3000"
    environment:
      - PORT=3000
      - NEXT_PUBLIC_SERVER_URL=http://server:3000
      - DATABASE_URL=${DATABASE_URL}
    restart: always
    networks:
      - shared_proxy

  server:
    image: ghcr.io/${GITHUB_REPOSITORY}/server:production
    container_name: mulai-plus-server-production
    ports:
      - "${PORT_SERVER:-3004}:3000"
    expose:
      - "3000"
    environment:
      - PORT=3000
      - DATABASE_URL=${DATABASE_URL}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - BETTER_AUTH_URL=${BETTER_AUTH_URL}
      - CORS_ORIGIN=https://mulaiplus.id
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - PAYMENT_API_URL=${PAYMENT_API_URL}
      - PAYMENT_API_KEY=${PAYMENT_API_KEY}
      - UNOSEND_API_KEY=${UNOSEND_API_KEY}
      - UNOSEND_FROM_EMAIL=${UNOSEND_FROM_EMAIL}
    restart: always
    networks:
      - shared_proxy

networks:
  shared_proxy:
    external: true
