services:
  web:
    image: ghcr.io/${GITHUB_REPOSITORY}/web:staging
    ports:
      - "127.0.0.1:${PORT_WEB}:3000"
    environment:
      - PORT=3000
      - NEXT_PUBLIC_SERVER_URL=${NEXT_PUBLIC_SERVER_URL}
      - DATABASE_URL=${DATABASE_URL}
    restart: always

  server:
    image: ghcr.io/${GITHUB_REPOSITORY}/server:staging
    ports:
      - "127.0.0.1:${PORT_SERVER}:3000"
    environment:
      - PORT=3000
      - DATABASE_URL=${DATABASE_URL}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - BETTER_AUTH_URL=${BETTER_AUTH_URL}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - PAYMENT_API_URL=${PAYMENT_API_URL}
      - PAYMENT_API_KEY=${PAYMENT_API_KEY}
    restart: always
