/** 38 provinsi Indonesia + slug URL — untuk landing SEO per-provinsi. */
export const PROVINCES: { name: string; slug: string }[] = [
  { name: "Aceh", slug: "aceh" },
  { name: "Sumatera Utara", slug: "sumatera-utara" },
  { name: "Sumatera Barat", slug: "sumatera-barat" },
  { name: "Riau", slug: "riau" },
  { name: "Kepulauan Riau", slug: "kepulauan-riau" },
  { name: "Jambi", slug: "jambi" },
  { name: "Sumatera Selatan", slug: "sumatera-selatan" },
  { name: "Bangka Belitung", slug: "bangka-belitung" },
  { name: "Bengkulu", slug: "bengkulu" },
  { name: "Lampung", slug: "lampung" },
  { name: "DKI Jakarta", slug: "dki-jakarta" },
  { name: "Jawa Barat", slug: "jawa-barat" },
  { name: "Banten", slug: "banten" },
  { name: "Jawa Tengah", slug: "jawa-tengah" },
  { name: "DI Yogyakarta", slug: "di-yogyakarta" },
  { name: "Jawa Timur", slug: "jawa-timur" },
  { name: "Bali", slug: "bali" },
  { name: "Nusa Tenggara Barat", slug: "nusa-tenggara-barat" },
  { name: "Nusa Tenggara Timur", slug: "nusa-tenggara-timur" },
  { name: "Kalimantan Barat", slug: "kalimantan-barat" },
  { name: "Kalimantan Tengah", slug: "kalimantan-tengah" },
  { name: "Kalimantan Selatan", slug: "kalimantan-selatan" },
  { name: "Kalimantan Timur", slug: "kalimantan-timur" },
  { name: "Kalimantan Utara", slug: "kalimantan-utara" },
  { name: "Sulawesi Utara", slug: "sulawesi-utara" },
  { name: "Gorontalo", slug: "gorontalo" },
  { name: "Sulawesi Tengah", slug: "sulawesi-tengah" },
  { name: "Sulawesi Barat", slug: "sulawesi-barat" },
  { name: "Sulawesi Selatan", slug: "sulawesi-selatan" },
  { name: "Sulawesi Tenggara", slug: "sulawesi-tenggara" },
  { name: "Maluku", slug: "maluku" },
  { name: "Maluku Utara", slug: "maluku-utara" },
  { name: "Papua", slug: "papua" },
  { name: "Papua Barat", slug: "papua-barat" },
  { name: "Papua Selatan", slug: "papua-selatan" },
  { name: "Papua Tengah", slug: "papua-tengah" },
  { name: "Papua Pegunungan", slug: "papua-pegunungan" },
  { name: "Papua Barat Daya", slug: "papua-barat-daya" },
];

export function provinceBySlug(slug: string) {
  return PROVINCES.find((p) => p.slug === slug);
}
